name: "Test and Build Website"

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Test and Build Website"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout main"
        uses: "actions/checkout@v4"

      - name: "Install Nix"
        uses: "DeterminateSystems/nix-installer-action@v19"

      - name: "Test and Build Website"
        run: |
          nix develop --command bash -c "npm ci && npm run test && npm run build"

      - name: "Fix Permissions of Website Artifacts"
        run: |
          chmod -c -R +rX "public/" | while read -r line; do
            echo "::warning title=Invalid file permissions automatically fixed::${line}"
          done

      - name: "Upload Website"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "public/"
