name: "Release, Build and Deploy Website"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "Release and Build Website"
    runs-on: "ubuntu-latest"
    outputs:
      release_created: "${{ steps.release.outputs.release_created }}"
    steps:
      - id: "release"
        uses: "googleapis/release-please-action@v4"

      - name: "Checkout main"
        if: "${{ steps.release.outputs.release_created }}"
        uses: "actions/checkout@v4"

      - name: "Install Nix"
        if: "${{ steps.release.outputs.release_created }}"
        uses: "DeterminateSystems/nix-installer-action@v19"

      - name: "Build Website"
        if: "${{ steps.release.outputs.release_created }}"
        run: |
          nix develop --command bash -c "npm ci && npm run build"

      - name: "Fix Permissions of Website Artifacts"
        if: "${{ steps.release.outputs.release_created }}"
        run: |
          chmod -c -R +rX "public/" | while read -r line; do
            echo "::warning title=Invalid file permissions automatically fixed::${line}"
          done

      - name: "Upload Website"
        if: "${{ steps.release.outputs.release_created }}"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "public/"

  deploy:
    name: "Deploy Website"
    needs: "build"
    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
        if: ${{ needs.build.outputs.release_created }}
